services:
  lutris:
    build: .
    image: lutris-selkies:latest
    privileged: true
    container_name: lutris
    security_opt:
      - seccomp:unconfined
    shm_size: "1gb"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
      - DRINODE=/dev/dri/renderD128
      - DRI_NODE=/dev/dri/renderD128
      - PIXELFLUX_WAYLAND=true
    ports:
      - "3000:3000"   # http
      - "3001:3001"   # https (recommended)
    volumes:
      - ./config:/config
    restart: unless-stopped

    # ----- Nvidia GPU users: uncomment this block, remove the devices: above
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
